# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

answer = 0

sequence = [1, 2]
term, index = 0, 2

while term < 4000000:
    term = sequence[index-1] + sequence[index-2]
    sequence.append(term)

    index += 1

for num in sequence:
    if num % 2 == 0:
        answer += num

print(answer)